# Generated by Django 5.2.8 on 2025-11-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_file_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
